################################
## Airflow Flower NetworkPolicy
#################################
{{- if (and .Values.networkPolicies.enabled (eq .Values.executor "CeleryExecutor")) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-flower-policy
  labels:
    tier: airflow
    component: airflow-flower-policy
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  podSelector:
    matchLabels:
      tier: airflow
      component: flower
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
{{- if .Values.platform.release }}
  ingress:
  - from:
    {{- if .Values.sidecar.enabled  }}
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress
    {{- else }}
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          tier: nginx
          component: ingress-controller
          release: {{ .Values.platform.release }}
    {{- end }}
    ports:
    - protocol: TCP
      port: {{ .Values.ports.flowerUI }}
{{- end }}
{{- end }}
