#############################
# ESO ExternalSecrets
#############################
{{- $root := . }}
{{- range $objName, $obj := .Values.externalSecrets.objects }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $root.Release.Name }}-{{ $objName }}
  namespace: {{ $root.Release.Namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: {{ $root.Values.externalSecrets.secretStore.kind }}
    name: {{ $root.Values.externalSecrets.secretStore.name }}
  target:
    template:
      type: {{ $obj.secretType }}
      metadata:
        {{- with $obj.annotations }}
        annotations: {{- default (dict) (tpl (toYaml $obj.annotations) $root) | nindent 10 }}
        {{- end }}
        {{- with $obj.labels }}
        labels: {{- default (dict) (tpl (toYaml $obj.labels) $root) | nindent 10 }}
        {{- end }}

    creationPolicy: Orphan
    name: {{ $root.Release.Name }}-{{ $objName }}
  {{- if $obj.secretKey }}
  data:
    - secretKey: {{ $obj.secretKey }}
      remoteRef:
        key: {{ $root.Release.Name }}-{{ $objName }}
  {{- else}}
  dataFrom:
    - extract:
        key: {{ $root.Release.Name }}-{{ $objName }}
  {{- end }}
{{- end }}
