#############################
# ESO ExternalSecrets
#############################
{{- $root := . }}
{{- range $objName, $obj := .Values.externalSecrets.objects }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $root.Release.Name }}-{{ $objName }}
  namespace: {{ $root.Release.Namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: {{ $root.Values.externalSecrets.secretStore.kind }}
    name: {{ $root.Values.externalSecrets.secretStore.name }}
  target:
    template:
      type: {{ $obj.secretType }}

      metadata:
        annotations: {{- default (dict) (tpl (toYaml $obj.annotations) $root) | nindent 10 }}
        labels: {{- default (dict) (tpl (toYaml $obj.labels) $root) | nindent 10 }}

    creationPolicy: Orphan
    name: {{ $root.Release.Name }}-{{ $objName }}
  data:
    - secretKey: connection
      remoteRef:
        key: {{ $root.Release.Name }}-{{ $objName }}
{{- end }}
