#############################
# ESO PushSecrets
#############################
{{- $root := . }}
{{- range $objName, $obj := .Values.externalSecrets.objects }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $root.Release.Name }}-{{ $objName }}
  namespace: {{ $root.Release.Namespace }}
spec:
  refreshInterval: {{ $root.Values.externalSecrets.pushSecret.refreshInterval }}
  secretStoreRefs:
    - name: {{ $root.Values.externalSecrets.secretStore.name }}
      kind: {{ $root.Values.externalSecrets.secretStore.kind }}
  selector:
    secret:
      name: {{ $root.Release.Name }}-{{ $objName }}
  data:
    - match:
        secretKey: {{ $obj.secretKey }}
        remoteRef:
          remoteKey: {{ $root.Release.Name }}-{{ $objName }}
      conversionStrategy: None
{{- end }}
