# apiVersion v2 is Helm 3
apiVersion: v2
name: airflow
version: 1.1.0-rc1
description: Helm chart to deploy the Astronomer Platform Airflow module
icon: https://airflow.apache.org/docs/apache-airflow/stable/_images/pin_large.png
keywords:
  - astronomer
  - airflow
dependencies:
  - name: airflow
    version: 1.4.0
    repository: https://airflow.apache.org
