apiVersion: v2
name: celery-exporter
version: 0.4.0
appVersion: 0.5.2
description: Prometheus exporter for Celery
type: application
home: https://github.com/danihodovic/celery-exporter
keywords:
  - celery
  - prometheus
  - exporter
