# Default values for celery-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: danihodovic/celery-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.5.2

imagePullSecrets: []
nameOverride: "celery-exporter"
fullnameOverride: "celery-exporter"
env:
- name: CE_BROKER_URL
  valueFrom:
    secretKeyRef:
      name: {{ .Release.name}}-broker-url
      key: connection

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 9808

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
