#################################
## dag-server ServiceAccount   ##
#################################
{{- if .Values.dagDeploy.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-dag-server
  labels:
    component: dag-server
    tier: airflow
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  annotations: {{- toYaml .Values.dagDeploy.serviceAccount.annotations | nindent 4 }}
{{- end }}
