######################
# dag server ingress #
######################
{{- if and .Values.ingress.enabled  .Values.dagDeploy.enabled }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-dag-server-ingress
  labels:
    tier: airflow
    component: dag-server-ingress
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.airflow.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
  {{- if or .Values.ingress.dagServerAnnotations .Values.authSidecar.annotations }}
  annotations:
  {{- if .Values.authSidecar.enabled  }}
{{- toYaml .Values.authSidecar.annotations | nindent 4 }}
  {{- else }}
    {{- if .Values.ingress.authCache.enabled }}
      "nginx.ingress.kubernetes.io/auth-cache-key": {{ .Values.ingress.authCache.key | quote }}
      "nginx.ingress.kubernetes.io/auth-cache-duration": {{ .Values.ingress.authCache.duration | quote }}
    {{- end }}
    {{ toYaml .Values.ingress.dagServerAnnotations | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - secretName: {{ .Values.ingress.tlsSecretName }}
      hosts:
        - {{- include "deployments_subdomain" . | indent 1 }}
        {{- if .Values.ingress.globalBaseDomain }}
        - {{- include "deployments_subdomain_global" . | indent 1 }}
        {{- end }}
  {{- end }}
  rules:
    - host: {{- include "deployments_subdomain" . | indent 1 }}
      http:
        paths:
          {{- if .Values.authSidecar.enabled  }}
          - path: /{{ .Release.Name }}/dags
          {{- else }}
          - path: /{{ .Release.Name }}/dags/(upload|downloads|healthz)(/.*)?
          {{- end }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-dag-server
                port:
                  {{- if .Values.authSidecar.enabled  }}
                  name: auth-proxy
                  {{- else }}
                  name: http
                  {{- end }}
    {{- if .Values.ingress.globalBaseDomain }}
    - host: {{- include "deployments_subdomain_global" . | indent 1 }}
      http:
        paths:
          {{- if .Values.authSidecar.enabled  }}
          - path: /{{ .Release.Name }}/dags
          {{- else }}
          - path: /{{ .Release.Name }}/dags/(upload|downloads|healthz)(/.*)?
          {{- end }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-dag-server
                port:
                  {{- if .Values.authSidecar.enabled  }}
                  name: auth-proxy
                  {{- else }}
                  name: http
                  {{- end }}
    {{- end }}
{{- end }}
