############################
## dag-server StatefulSet ##
############################
{{- if .Values.dagDeploy.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-dag-server
  labels:
    component: dag-server
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Release.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.dagDeploy.persistence.enabled .Values.dagDeploy.persistence.persistentVolumeClaimRetentionPolicy }}
  persistentVolumeClaimRetentionPolicy: {{- toYaml .Values.dagDeploy.persistence.persistentVolumeClaimRetentionPolicy  | nindent 4 }}
  {{ end }}
  serviceName: {{ include "airflow.fullname" . }}-dag-server
  replicas: 1
  selector:
    matchLabels:
      component: dag-server
      tier: airflow
      release: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}-dag-server
  template:
    metadata:
      labels:
        component: dag-server
        tier: airflow
        release: {{ .Release.Name }}
        chart: "{{ .Release.Name }}-{{ .Chart.Version }}"
        heritage: {{ .Release.Service }}
        {{- with .Values.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if or .Values.airflow.registry.secretName .Values.airflow.registry.connection }}
      imagePullSecrets:
        - name: {{ template "astro.registry_secret" . }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-dag-server
      securityContext: {{ toYaml .Values.dagDeploy.securityContexts.pod | nindent 8 }}
      containers:
        - name: dag-server
          image: "{{ .Values.dagDeploy.images.dagServer.repository }}:{{ .Values.dagDeploy.images.dagServer.tag }}"
          imagePullPolicy: {{ .Values.dagDeploy.images.dagServer.pullPolicy }}
          command: ["sanic", "dag_deploy.server.app", "-H", "0.0.0.0"]
          ports:
          - name: server
            containerPort: {{ .Values.dagDeploy.ports.dagServerHttp }}
          securityContext: {{ toYaml .Values.dagDeploy.securityContexts.container  | nindent 12 }}
          resources:
            {{- toYaml .Values.dagDeploy.resources | nindent 12 }}
          env:
          - name: HOUSTON_SERVICE_ENDPOINT
            value: "http://{{ .Values.platform.release }}-houston.{{ .Values.platform.namespace }}.svc.cluster.local.:8871/v1/"
{{- if .Values.dagDeploy.extraEnv }}
{{ toYaml .Values.dagDeploy.extraEnv | indent 10 }}
{{- end }}
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: {{ .Values.dagDeploy.ports.dagServerHttp }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.dagDeploy.ports.dagServerHttp }}
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
          - name: data
            mountPath: /data
            readOnly: false
{{- if .Values.authSidecar.enabled }}
        - name: auth-proxy
          image: "{{ .Values.authSidecar.repository }}:{{ .Values.authSidecar.tag }}"
          imagePullPolicy: {{ .Values.authSidecar.pullPolicy }}
          {{- if .Values.authSidecar.resources }}
          resources: {{- toYaml .Values.authSidecar.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.authSidecar.securityContext }}
          securityContext: {{- toYaml .Values.authSidecar.securityContext | nindent 12 }}
          {{- end }}
          ports:
          - containerPort: {{ .Values.authSidecar.port }}
            name: auth-proxy
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.authSidecar.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.authSidecar.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            name: nginx-sidecar-conf
            subPath: nginx.conf
{{- end }}
{{- if .Values.dagDeploy.extraContainers }}
{{- toYaml .Values.dagDeploy.extraContainers | nindent 8 }}
{{- end }}
{{- if .Values.authSidecar.enabled }}
      volumes:
      - name: nginx-sidecar-conf
        configMap:
          name: {{ .Release.Name }}-dag-server-nginx-conf
{{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
      {{- if .Values.dagDeploy.persistence.annotations }}
      annotations:
        {{- toYaml .Values.dagDeploy.persistence.annotations | nindent 10 }}
      {{- end }}
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.dagDeploy.persistence.size }}
      {{- if .Values.dagDeploy.persistence.storageClass }}
      storageClassName: {{ .Values.dagDeploy.persistence.storageClass }}
      {{- end }}
{{- end }}
