#################################
## dag-server ServiceAccount   ##
#################################
{{- if and .Values.dagDeploy.enabled .Values.dagDeploy.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "astro.dagDeploy.serviceAccountName" . }}
  labels:
    component: dag-server
    tier: airflow
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  annotations: {{- toYaml .Values.dagDeploy.serviceAccount.annotations | nindent 4 }}
{{- end }}
