#################################
# dag-deploy-rolebinding
#################################
{{- if and .Values.dagDeploy.enabled .Values.dagDeploy.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: {{ .Release.Name }}-dag-server-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ template "astro.dagDeploy.serviceAccountName" . }}
  namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: Role
  name: {{ .Release.Name }}-dag-server-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: {{ .Release.Name }}-dag-downloader-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "astro.webserver.serviceAccountName" . }}
  namespace: "{{ .Release.Namespace }}"
- kind: ServiceAccount
  name: {{ include "astro.triggerer.serviceAccountName" . }}
  namespace: "{{ .Release.Namespace }}"
- kind: ServiceAccount
  name: {{ include "astro.worker.serviceAccountName" . }}
  namespace: "{{ .Release.Namespace }}"
- kind: ServiceAccount
  name: {{ include "astro.scheduler.serviceAccountName" . }}
  namespace: "{{ .Release.Namespace }}"
{{- if .Values.airflow.dagProcessor.enabled }}
- kind: ServiceAccount
  name: {{ include "astro.dagProcessor.serviceAccountName" . }}
  namespace: "{{ .Release.Namespace }}"
{{- end }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-dag-downloader-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
