#################################
## dag-server ServiceAccount   ##
#################################
{{- if and .Values.gitSyncRelay.enabled .Values.gitSyncRelay.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "astro.gitSyncRelay.serviceAccountName" . }}
  labels:
    component: git-sync-relay
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Release.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
  annotations: {{- toYaml .Values.gitSyncRelay.serviceAccount.annotations | nindent 4 }}
{{- end }}
