########################
## git-sync-relay pvc ##
########################
{{- if and .Values.gitSyncRelay.enabled ( eq .Values.gitSyncRelay.mode "shared_volume") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-git-data
  labels:
    component: git-sync-relay
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Release.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
    # - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.gitSyncRelay.volumeSync.volumeSize }}
  storageClassName: {{ .Values.gitSyncRelay.volumeSync.storageClassName }}
{{- end }}
