###########################################
## Pgbouncer SSL Pre install/update Hook ##
###########################################
{{- if and .Values.gitSyncRelay.enabled ( eq .Values.gitSyncRelay.repoShareMode "shared_volume" ) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-git-sync-relay-job
  labels:
    component: git-sync-relay
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Release.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "5"
spec:
  template:
    metadata:
      labels:
        component: git-sync-relay
        tier: airflow
        release: {{ .Release.Name }}
        chart: "{{ .Release.Name }}-{{ .Chart.Version }}"
        heritage: {{ .Release.Service }}
    spec:
      {{- if or .Values.airflow.registry.secretName .Values.airflow.registry.connection }}
      imagePullSecrets:
        - name: {{ template "astro.registry_secret" . }}
      {{- end }}
      restartPolicy: Never
      serviceAccountName: "default"
      securityContext: {{ toYaml .Values.gitSyncRelay.securityContext | nindent 8 }}
      volumes:
        - name: git-repo-contents
        {{- if eq .Values.gitSyncRelay.repoShareMode "shared_volume" }}
          persistentVolumeClaim:
            claimName: git-repo-contents
        {{- end }}
        {{- if .Values.gitSyncRelay.repo.sshPrivateKeySecretName }}
        - name: git-secret
          secret:
            secretName: {{ .Values.gitSyncRelay.repo.sshPrivateKeySecretName }}
        {{- end }}
        - name: {{ .Release.Name }}-git-sync-config
          configMap:
            name: {{ .Release.Name }}-git-sync-config
        {{- if .Values.loggingSidecar.enabled }}
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-sidecar-config
        - emptyDir: {}
          name: sidecar-logging-consumer
        {{- end }}
        {{- if and .Values.authSidecar.enabled (eq .Values.gitSyncRelay.repoFetchMode "webhook") }}
        - name: nginx-sidecar-conf
          configMap:
            name: {{ .Release.Name }}-git-sync-relay-nginx-conf
        {{- end }}
      containers:
        - name: "git-sync"
          image: "{{ .Values.gitSyncRelay.images.gitSync.repository }}:{{ .Values.gitSyncRelay.images.gitSync.tag }}"
          volumeMounts:
            {{- if .Values.gitSyncRelay.repo.sshPrivateKeySecretName }}
            - name: git-secret
              mountPath: /etc/git-secret/ssh
              readOnly: true
              subPath: gitSshKey
            {{- if .Values.gitSyncRelay.repo.knownHosts }}
            - name: {{ .Release.Name }}-git-sync-config
              mountPath: /etc/git-secret/known_hosts
              readOnly: true
              subPath: known_hosts
            {{- end }}
            {{- end }}
            - name: git-repo-contents
              mountPath: /git
          env:
            - name: GIT_SYNC_ROOT
              value: "/git"
            - name: GIT_SYNC_REPO
              value: "{{ .Values.gitSyncRelay.repo.url }}"
            - name: GIT_SYNC_BRANCH
              value: "{{ .Values.gitSyncRelay.repo.branch }}"
            - name: GIT_SYNC_DEPTH
              value: "{{ .Values.gitSyncRelay.repo.depth }}"
            - name: GIT_SYNC_WAIT
              value: "{{ .Values.gitSyncRelay.repo.wait }}"
            {{- if .Values.gitSyncRelay.repoFetchMode }}
            - name: GIT_SYNC_REPO_FETCH_MODE
              value: "{{ .Values.gitSyncRelay.repoFetchMode }}"
            {{- end }}
            {{- if .Values.gitSyncRelay.webhookSecretKey }}
            - name: GIT_SYNC_WEBHOOK_SECRET
              value: "{{ .Values.gitSyncRelay.webhookSecretKey }}"
            {{- end }}
            {{- if .Values.gitSyncRelay.repo.sshPrivateKeySecretName }}
            - name: GIT_SYNC_SSH
              value: "true"
            - name: GIT_SSH_KEY_FILE
              value: "/etc/git-secret/ssh"
            {{- if .Values.gitSyncRelay.repo.knownHosts }}
            - name: GIT_KNOWN_HOSTS
              value: "true"
            - name: GIT_SSH_KNOWN_HOSTS_FILE
              value: "/etc/git-secret/known_hosts"
            {{- else }}
            - name: GIT_KNOWN_HOSTS
              value: "false"
            {{- end }}
            {{- end }}
          {{- if .Values.gitSyncRelay.gitSync.livenessProbe  }}
          livenessProbe: {{ tpl (toYaml .Values.gitSyncRelay.gitSync.livenessProbe) . | nindent 12 }}
          {{- end }}
          {{- if .Values.gitSyncRelay.gitSync.readinessProbe  }}
          readinessProbe: {{ tpl (toYaml .Values.gitSyncRelay.gitSync.readinessProbe) . | nindent 12 }}
          {{- end }}
          resources: {{- toYaml .Values.gitSyncRelay.gitSync.resources | nindent 12 }}

{{ end }}
