########################
## git-sync-relay pvc ##
########################
# .Values.gitSyncRelay.mode = {{ .Values.gitSyncRelay.mode }}
{{- if and .Values.gitSyncRelay.enabled ( eq .Values.gitSyncRelay.mode "shared_volume") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-git-sync-relay
  labels:
    component: git-sync-relay
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Release.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.gitSyncRelay.volumeSync.volumeSize }}
{{- end }}
