########################
## git-sync-relay pvc ##
########################
{{- if and
  .Values.gitSyncRelay.enabled
  (eq .Values.gitSyncRelay.repoShareMode "shared_volume")
}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-repo-contents
  labels:
    component: git-sync-relay
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Release.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.gitSyncRelay.volumeSync.volumeSize }}
  storageClassName: {{ .Values.gitSyncRelay.volumeSync.storageClassName }}
{{- end }}
