############################
## git-sync-relay Service ##
############################
{{- if .Values.gitSyncRelay.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-git-sync-relay
  labels:
    component: git-sync-relay
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Release.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: git
      port: 9418
      protocol: TCP
      targetPort: 9418
  selector:
    component: git-sync-relay
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Release.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- end -}}
