#################################
## dag-server ServiceAccount   ##
#################################
{{- if .Values.dagServer.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-dag-server
  labels:
    component: dag-server
    tier: airflow
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- toYaml .Values.dagServer.serviceAccount.annotations | nindent 4 }}
{{- end }}