#################################
# dag-server-role-binding
#################################
{{- if .Values.dagServer.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: {{ .Release.Name }}-dag-server-role-binding
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-dag-server
  namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: Role
  name: {{ .Release.Name }}-dag-server-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
