############################
## dag-server StatefulSet ##
############################
{{- if .Values.dagServer.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-dag-server
  labels:
    component: dag-server
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Release.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  serviceName: {{ include "airflow.fullname" . }}-dag-server
  replicas: 1
  selector:
    matchLabels:
      component: dag-server
      tier: airflow
      release: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}-dag-server
  template:
    metadata:
      labels:
        component: dag-server
        tier: airflow
        release: {{ .Release.Name }}
        chart: "{{ .Release.Name }}-{{ .Chart.Version }}"
        heritage: {{ .Release.Service }}
        {{- with .Values.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Release.Name }}-dag-server
      securityContext: {{ toYaml .Values.dagServer.securityContext | nindent 8 }}
      containers:
        - name: dag-server
          image: "{{ .Values.dagServer.images.dagServer.repository }}:{{ .Values.dagServer.images.dagServer.tag }}"
          imagePullPolicy: {{ .Values.dagServer.images.dagServer.pullPolicy }}
          ports:
          - name: server
            containerPort: {{ .Values.dagServer.ports }}
          resources:
            {{- toYaml .Values.dagServer.resources | nindent 12 }}
          env:
{{- if .Values.dagServer.extraEnv }}
{{ toYaml .Values.dagServer.extraEnv | indent 10 }}
{{- end }}
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: {{ .Values.dagServer.ports }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.dagServer.ports }}
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
          - name: data
            mountPath: /data
            readOnly: true
  volumeClaimTemplates:
  - metadata:
      name: data
      {{- if .Values.dagServer.persistence.annotations }}
      annotations:
        {{- toYaml .Values.dagServer.persistence.annotations | nindent 10 }}
      {{- end }}
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.dagServer.persistence.size }}
      {{- if .Values.dagServer.persistence.storageClass }}
      storageClassName: {{ .Values.dagServer.persistence.storageClass }}
      {{- end }}
{{- end }}
