###########################
## dag-server configmap
###########################
{{- if and .Values.dagServer.enabled .Values.dagServer.repo.knownHosts }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-dag-server-config
  labels:
    component: {{ .Release.Name }}-dag-server
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Release.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
data:
  something: |
    {{- .Values.dagServer.something | nindent 4 }}
{{- end }}
