###########################################
## Event Exporter ConfigMap              ##
###########################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-event-exporter-config"
  namespace: "{{ .Release.Namespace }}"
  labels:
    component: event-exporter
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
data:
  config.yaml: |-
    namespace: "{{ .Release.Namespace }}"
    logLevel: info
    logFormat: json
    # To address client-side throttling errors
    kubeQPS: 100
    kubeBurst: 500
    # Increase maxEventsAgeSeconds for demo purposes
    # Allows capture of all events in the last hour
    maxEventsAgeSeconds: 3600
    #metricsNamePrefix: event_exporter_
    route:
      routes:
        - match:
            - receiver: "dump"
          drop:
            - type: "Normal"
    receivers:
      #{{- if .Values.airflow.elasticsearch.enabled  }}
      #- name: "elasticsearch-receiver"
      #  elasticsearch:
      #    hosts:
      #      - "http://{{ .Values.airflow.elasticsearch.connection.host }}:{{ .Values.airflow.elasticsearch.connection.port }}"
      #    index: {{ .Release.Name }}-kube-events
      #    # Ca be used optionally for time based indices, accepts Go time formatting directives
      #    #indexFormat: "fluentd.{{ .Release.Name }}-kube-events"
      #    username: {{ .Values.airflow.elasticsearch.connection.user }}
      #    password: {{ .Values.airflow.elasticsearch.connection.pass }}
      #{{- end }}
      - name: dump
        stdout:
          deDot: false
