############################
## dag-server StatefulSet ##
############################
{{- $nodeSelector := or .Values.eventExporter.nodeSelector .Values.airflow.nodeSelector }}
{{- $affinity := or .Values.eventExporter.affinity .Values.airflow.affinity }}
{{- $tolerations := or .Values.eventExporter.tolerations .Values.airflow.tolerations }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-event-exporter"
  namespace: "{{ .Release.Namespace }}"
  labels:
    component: event-exporter
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Release.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: event-exporter
      tier: airflow
  template:
    metadata:
      labels:
        component: event-exporter
        tier: airflow
        release: {{ .Release.Name }}
        chart: "{{ .Release.Name }}-{{ .Chart.Version }}"
        heritage: {{ .Release.Service }}
        {{- if .Values.labels }}
        {{- .Values.labels | toYaml | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/kubernetes-events-exporter/event-exporter-configmap.yaml") . | sha256sum }}
        prometheus.io/scrape: 'true'
        prometheus.io/port: '2112'
        prometheus.io/path: '/metrics'
    spec:
      {{- if or .Values.airflow.registry.secretName .Values.airflow.registry.connection }}
      imagePullSecrets:
        - name: {{ template "astro.registry_secret" . }}
      {{- end }}
      nodeSelector: {{- toYaml $nodeSelector | nindent 8 }}
      affinity: {{- toYaml $affinity | nindent 8 }}
      tolerations: {{- toYaml $tolerations | nindent 8 }}
      serviceAccountName: {{ template "astro.eventExporter.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: event-exporter
          image: "{{ .Values.eventExporter.images.eventServer.repository }}:{{ .Values.eventExporter.images.eventServer.tag }}"
          imagePullPolicy: "{{ .Values.eventExporter.images.eventServer.imagePullPolicy }}"
          args:
            - -conf=/data/config.yaml
          volumeMounts:
            - mountPath: /data
              name: cfg
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
      volumes:
        - name: cfg
          configMap:
            name: "{{ .Release.Name }}-event-exporter-config"
