###################################
## event-exporter ServiceAccount ##
###################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "astro.eventExporter.serviceAccountName" . }}
  labels:
    component: event-exporter
    tier: airflow
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  annotations: {{- toYaml .Values.eventExporter.serviceAccount.annotations | nindent 4 }}
