################################
## Event Exporter  RoleBinding ##
################################
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-event-exporter-rolebinding"
  namespace: "{{ .Release.Namespace }}"
  labels:
    component: event-exporter
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Release.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ .Release.Name }}-event-exporter-role"
subjects:
  - kind: ServiceAccount
    namespace: "{{ .Release.Namespace }}"
    name: "{{ .Release.Name }}-event-exporter"
