###########################################
## Event Exporter ConfigMap              ##
###########################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-event-exporter-config"
  namespace: "{{ .Release.Namespace }}"
  labels:
    component: event-exporter
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
data:
  config.yaml: |
    namespace: "{{ .Release.Namespace }}"
    logLevel: warn
    logFormat: json
    metricsNamePrefix: event_exporter_
    route:
      routes:
        - match:
            - receiver: "dump"
          drop:
            - type: "Normal"
      #drop:
      #  - type: "Normal"
      #  # This a final route for user messages
      #- match:
      #    - kind: "Pod|Deployment|ReplicaSet|StatefulSet"
      #      receiver: "dump"
    receivers:
      - name: "dump"
        stdout: {}
