
{{- if (and .Values.workers.keda.enabled (eq .Values.executor "CeleryExecutor")) }}
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-worker
  namespace: {{  .Release.Namespace }}
  labels:
    deploymentName: {{ .Release.Name }}-worker
spec:
  scaleTargetRef:
    deploymentName: {{ .Release.Name }}-worker
  pollingInterval:  {{  .Values.workers.keda.pollingInterval }}   # Optional. Default: 30 seconds
  cooldownPeriod: {{  .Values.workers.keda.cooldownPeriod }}    # Optional. Default: 300 seconds
  maxReplicaCount: {{  .Values.workers.keda.maxReplicaCount }}   # Optional. Default: 100
  triggers:
    - type: postgres
      metadata:
        connStr: AIRFLOW_CONN_AIRFLOW_DB
        query: "SELECT ceil(COUNT(*)::decimal / 16) FROM task_instance WHERE state='running' OR state='queued'"
---
{{- end }}
