{{- $additionalVolume := .Values.workers.additionalVolume }}
{{- if and $additionalVolume.enabled (eq .Values.executor "CeleryExecutor")}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-worker-pv
  labels:
    tier: airflow
    component: worker
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  capacity:
    storage: {{ default "5Gi" $additionalVolume.capacity }}
  volumeMode: {{ default "Filesystem" $additionalVolume.volumeMode }}
  accessModes:
    - {{ default "ReadWriteMany" $additionalVolume.accessMode }}
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ $additionalVolume.storageClassName }}
{{- toYaml $additionalVolume.volumePlugin | nindent 2 }}
{{- end }}
