{{- $additionalVolume := .Values.workers.additionalVolume }}
{{- if and $additionalVolume.enabled (eq .Values.executor "CeleryExecutor")}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-worker-claim
  labels:
    tier: airflow
    component: worker
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ default "ReadWriteMany" $additionalVolume.accessMode }}
  storageClassName: {{ $additionalVolume.storageClassName }}
  resources:
    requests:
      storage: {{ default "5Gi" $additionalVolume.capacity }}
{{- end }}
