apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "prometheus-redis-exporter.fullname" . }}
  labels:
{{ include "prometheus-redis-exporter.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.annotations | indent 8 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "prometheus-redis-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
{{ toYaml .Values.annotations | indent 8 }}
      labels:
{{ include "prometheus-redis-exporter.labels" . | indent 8 }}
      {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ template "prometheus-redis-exporter.serviceAccountName" . }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          {{- range $key, $value := .Values.extraArgs }}
            - --{{ $key }}={{ $value }}
          {{- end }}
          securityContext:
          {{- range $key, $value := .Values.securityContext }}
            {{ $key }}: {{ $value }}
          {{- end }}
          ports:
            - name: exporter-port
              containerPort: 9121
          env:
            - name: REDIS_ADDR
            {{- if .Values.redisAddressConfig.enabled }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.redisAddressConfig.configmap.name }}
                  key: {{ .Values.redisAddressConfig.configmap.key }}
            {{- else }}
              value: {{ .Values.redisAddress }}
            {{- end }}
          {{- if .Values.auth.enabled }}
            - name: REDIS_PASSWORD
            {{- if .Values.auth.secret.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.secret.name }}
                  key: {{ .Values.auth.secret.key }}
            {{- else }}
              value: {{ .Values.auth.redisPassword }}
            {{- end }}
            {{- if .Values.auth.redisUser }}
            - name: REDIS_USER
              value: {{ .Values.auth.redisUser }}
            {{- end }}
          {{- end }}
{{- if .Values.script }}
            - name: REDIS_EXPORTER_SCRIPT
              value: /script/script.lua
{{- end }}
{{- if .Values.env }}
{{ toYaml .Values.env | indent 12 }}
{{- end }}
{{- if .Values.script }}
          volumeMounts:
              - mountPath: /script
                name: script-mount
{{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: exporter-port
          readinessProbe:
            httpGet:
              path: /
              port: exporter-port
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.script }}
      volumes:
        - name: script-mount
          configMap:
             name: {{ .Values.script.configmap }}
             items:
              - key: {{ .Values.script.keyname }}
                path: script.lua
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
