###########################################
## Redis Exporter ServiceAccount        ##
###########################################
{{- if and .Values.astronomer.redisExporter.enabled (eq .Values.airflow.executor "CeleryExecutor") }}
{{- if .Values.astronomer.redisExporter.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-redis-exporter.serviceAccountName" . }}
  labels:
{{ include "prometheus-redis-exporter.labels" . | indent 4 }}
{{- end -}}
{{- end }}