###########################################
## Redis Exporter ServiceAccount        ##
###########################################
{{- if and .Values.astronomer.redisExporter.enabled (eq .Values.airflow.executor "CeleryExecutor") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-redis-exporter
  labels:
{{ include "prometheus-redis-exporter.labels" . | indent 4 }}
{{- end }}
