###########################################
##     Redis Exporter Service            ##
###########################################
{{- if and .Values.astronomer.redisExporter.enabled (eq .Values.airflow.executor "CeleryExecutor") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-exporter
  labels:
    tier: airflow
    component: redis-exporter
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: redis-exporter
      port: 9121
      targetPort: exporter-port
      protocol: TCP
  selector:
    {{- include "prometheus-redis-exporter.selectorLabels" . | nindent 4 }}
{{- end }}
