{{- if .Values.sccEnabled }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    release.openshift.io/create-only: "true"
    "helm.sh/hook": "pre-install,pre-upgrade"
  name: {{ .Release.Name }}-anyuid
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{ .Release.Namespace }}:default
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "astro.webserver.serviceAccountName" . }}
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "astro.redis.serviceAccountName" . }}
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "astro.flower.serviceAccountName" . }}
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "astro.scheduler.serviceAccountName" . }}
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "astro.statsd.serviceAccountName" . }}
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "astro.createUserJob.serviceAccountName" . }}
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "astro.migrateDatabaseJob.serviceAccountName" . }}
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "astro.worker.serviceAccountName" . }}
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "astro.triggerer.serviceAccountName" . }}
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "astro.pgbouncer.serviceAccountName" . }}
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "astro.cleanup.serviceAccountName" . }}
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
{{- end }}
