################################
## Airflow Create User Job
#################################
{{- if .Values.webserver.defaultUser.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-create-user
  labels:
    tier: airflow
    component: create-user-job
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        tier: airflow
        component: create-user-job
        release: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      containers:
        - name: create-user
          image: {{ template "airflow_image" . }}
          imagePullPolicy: {{ .Values.images.airflow.pullPolicy }}
          args:
            - "users"
            - "create"
            - "--role"
            - {{ .Values.webserver.defaultUser.role }}
            - "--username"
            - {{ .Values.webserver.defaultUser.username }}
            - "--email"
            - {{ .Values.webserver.defaultUser.email }}
            - "--firstname"
            - {{ .Values.webserver.defaultUser.firstName }}
            - "--lastname"
            - {{ .Values.webserver.defaultUser.lastName }}
            - "--password"
            - {{ .Values.webserver.defaultUser.password }}
          env:
          {{- include "custom_airflow_environment" . | indent 10 }}
          {{- include "standard_airflow_environment" . | indent 10 }}
          volumeMounts:
            - name: config
              mountPath: {{ template "airflow_config_path" . }}
              subPath: airflow.cfg
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ template "airflow_config" . }}
{{- end }}
