################################
## Airflow Run Migrations Job
#################################
{{ $ctx := . }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-run-airflow-migrations
  labels:
    tier: airflow
    component: run-airflow-migrations
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        tier: airflow
        component: run-airflow-migrations
        release: {{ .Release.Name }}
      {{- if .Values.runMigrationsJobAnnotations }}
      annotations:
        {{- range $k, $v := .Values.runMigrationsJobAnnotations }}
        {{ $k | quote }}: {{ tpl $v $ctx | toYaml }}
    {{- end }}
    {{- end }}
    spec:
      securityContext:
        runAsUser: {{ .Values.uid }}
      restartPolicy: OnFailure
      {{- if .Values.nodeSelector }}
      nodeSelector:
      {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
      {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
      {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}

      {{- if or .Values.registry.secretName .Values.registry.connection }}
      imagePullSecrets:
        - name: {{ template "registry_secret" . }}
      {{- end }}
      containers:
        - name: run-airflow-migrations
          image: {{ template "default_airflow_image" . }}
          imagePullPolicy: {{ .Values.images.airflow.pullPolicy }}
          {{- if semverCompare ">=2.0.0" .Values.airflowVersion }}
          args: ["airflow", "db", "upgrade"]
          {{- else }}
          args: ["airflow", "upgradedb"]
          {{- end }}
          env:
          {{- include "standard_airflow_environment" . | indent 10 }}
          volumeMounts:
            - name: config
              mountPath: {{ template "airflow_config_path" . }}
              subPath: airflow.cfg
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ template "airflow_config" . }}
