---
# Are we using a local/sequential executor?
{{- $local := or (eq .Values.executor "LocalExecutor") (eq .Values.executor "SequentialExecutor") }}
# Are we using the kubernetes executor?
{{- $kube := eq .Values.executor "KubernetesExecutor" }}
# Is persistence enabled on the _workers_?
# This is important because in $local mode, the scheduler assumes the role of the worker
{{- $persistence := .Values.workers.persistence.enabled }}
# If we're using a StatefulSet
{{- $stateful := and $local $persistence }}
# If we're using elasticsearch logging
{{- $elasticsearch := .Values.elasticsearch.enabled }}

apiVersion: v1
kind: Pod
metadata:
  name: dummy-name
  labels:
    tier: airflow
    component: worker
    release: '{{ .Release.Name }}'
    platform: "{{ .Values.platform.release }}"
    workspace: "{{ .Values.platform.workspace }}"
spec:
{{- if .Values.workers.extraInitContainers }}
  initContainers:
{{- toYaml .Values.workers.extraInitContainers | nindent 4 }}
{{- end }}
  containers:
    - args: []
      name: "base"
      command: []
      {{/* Environment section duplicated from _helpers.yaml file */}}
      {{- if .Values.mountAllFromSecretName }}
      envFrom:
      {{- include "custom_airflow_environment_mount_all" . | indent 8 }}
      env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: LocalExecutor
      {{- include "standard_airflow_environment" . | indent 6 }}
      {{- else }}
      env:
      {{- include "custom_airflow_environment_mount_individual" . | indent 6 }}
      {{- include "standard_airflow_environment" . | indent 6 }}
      {{- end }}
      image: {{ template "airflow_image" . }}
      imagePullPolicy: {{ .Values.images.airflow.pullPolicy }}
      name: base
      ports: []
      volumeMounts:
        - mountPath: {{ template "airflow_logs" . }}
          name: airflow-logs
        - name: airflow-config
          mountPath: {{ template "airflow_config_path" . }}
          subPath: airflow.cfg
          readOnly: true
        - name: airflow-config
          mountPath: {{ template "airflow_local_setting_path" . }}
          subPath: airflow_local_settings.py
          readOnly: true
{{- if .Values.workers.extraVolumeMounts }}
{{ toYaml .Values.workers.extraVolumeMounts | indent 8 }}
{{- end }}
{{- if .Values.workers.extraContainers }}
{{- toYaml .Values.workers.extraContainers | nindent 4 }}
{{- end }}
  hostNetwork: false
  {{- if or .Values.registry.secretName .Values.registry.connection }}
  imagePullSecrets:
    - name: {{ template "registry_secret" . }}
  {{- end }}
  restartPolicy: Never
  securityContext:
    runAsUser: {{ .Values.uid }}
    fsGroup: {{ .Values.gid }}
  nodeSelector: {{ toYaml .Values.nodeSelector | nindent 4 }}
  affinity: {{ toYaml .Values.affinity | nindent 4 }}
  tolerations: {{ toYaml .Values.tolerations | nindent 4 }}
  serviceAccountName: '{{ .Release.Name }}-worker-serviceaccount'
  volumes:
  - configMap:
      name: {{ include "airflow_config" . }}
    name: airflow-config
{{- if .Values.workers.extraVolumes }}
{{ toYaml .Values.workers.extraVolumes | indent 2 }}
{{- end }}
{{- if not $stateful }}
  - name: airflow-logs
    emptyDir: {}
{{- else }}
  volumeClaimTemplates:
    - metadata:
      name: airflow-logs
    spec:
    {{- if .Values.workers.persistence.storageClassName }}
    storageClassName: {{ .Values.workers.persistence.storageClassName }}
    {{- end }}
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: {{ .Values.workers.persistence.size }}
{{- end }}
