apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-celery-exporter
  labels:
    tier: airflow
    component: celery-exporter
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 9808
      targetPort: http
      protocol: TCP
      name: celery-exporter
  selector:
    {{- include "celery-exporter.selectorLabels" . | nindent 4 }}
