{{- if and .Values.astronomer.redisExporter.enabled (eq .Values.airflow.executor "CeleryExecutor") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-celery-exporter
  labels:
    {{- include "celery-exporter.labels" . | nindent 4 }}
{{- end }}
